apiVersion: 1

datasources:
  - name: postgresql
    uid: postgresql
    type: postgres
    access: proxy
    url: postgresql:5432
    user: postgres

    secureJsonData:
      password: postgres

    jsonData:
      database: iotdata
      sslmode: disable
      postgresVersion: 15
      timescaledb: false

    isDefault: true