{
 "title": "Forecast",
 "time": { "from": "2013-09-03T22:00:00.000Z", "to": "2013-09-03T23:30:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "window_size",
    "query": {
     "query": "SELECT DISTINCT slice_gap\r\nFROM plug_data_expected\r\nORDER BY slice_gap;"
    }
   },
   {
    "name": "house",
    "query": {
     "query": "SELECT DISTINCT house_id\r\nFROM plug_data_expected\r\nWHERE slice_gap = ${window_size}\r\nORDER BY house_id;"
    }
   },
   {
    "name": "household",
    "query": {
     "query": "SELECT DISTINCT household_id\r\nFROM plug_data_expected\r\nWHERE house_id = ${house}\r\nAND slice_gap = ${window_size}\r\nORDER BY household_id;"
    }
   },
   {
    "name": "plug",
    "query": {
     "query": "SELECT DISTINCT plug_id\r\nFROM plug_data_expected\r\nWHERE house_id = ${house}\r\nAND household_id = ${household}\r\nAND slice_gap = ${window_size}\r\nORDER BY plug_id;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Plug forecast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS average_load_expected\r\nFROM plug_data_expected\r\nWHERE house_id = ${house}\r\n  AND household_id = ${household}\r\n  AND plug_id = ${plug}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS average_load\r\nFROM plug_data\r\nWHERE house_id = ${house}\r\n  AND household_id = ${household}\r\n  AND plug_id = ${plug}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS forecast_load_expected\r\nFROM plug_data_forecast_expected\r\nWHERE house_id = ${house}\r\n  AND household_id = ${household}\r\n  AND plug_id = ${plug}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;\r\n"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS forecast_load\r\nFROM plug_data_forecast\r\nWHERE house_id = ${house}\r\n  AND household_id = ${household}\r\n  AND plug_id = ${plug}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "House forecast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS average_load_expected\r\nFROM house_data_expected\r\nWHERE house_id = ${house}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS average_load\r\nFROM house_data\r\nWHERE house_id = ${house}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS forecast_load_expected\r\nFROM house_data_forecast_expected\r\nWHERE house_id = ${house}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;\r\n"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  avg AS forecast_load\r\nFROM house_data_forecast\r\nWHERE house_id = ${house}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Plug forecast latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  prediction_latency as forecast_latency\r\nFROM plug_data_forecast \r\nWHERE house_id = ${house}\r\n  AND household_id = ${household}\r\n  AND plug_id = ${plug}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "House forecast latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\r\n  make_timestamp(\r\n      year::INTEGER,\r\n      month::INTEGER,\r\n      day::INTEGER,\r\n      0,\r\n      0,\r\n      0\r\n  ) + (slice_index * slice_gap * INTERVAL '1 minute') AS time,\r\n  prediction_latency as forecast_latency\r\nFROM house_data_forecast \r\nWHERE house_id = ${house}\r\n  AND slice_gap = ${window_size}\r\nORDER BY time;"
    }
   ]
  }
 ]
}